import numpy as np
import numpy.typing as npt


def gpu_sort(input: npt.NDArray[np.float32]) -> npt.NDArray[np.float32]: ...
def gpu_reduce(input: npt.NDArray[np.float32], op: str = "sum") -> float: ...
def gpu_prefix_scan(input: npt.NDArray[np.float32]) -> npt.NDArray[np.float32]: ...
def gpu_matmul(
    a: npt.NDArray[np.float32], b: npt.NDArray[np.float32]
) -> npt.NDArray[np.float32]: ...
